# Edgar - Companies that are dropped out by Mutual Funds

#### Now that we have a list of companies and their holdings for a set of Mutual Funds, lets check which of these companies have been dropped out of the Mutual Funds' portfolios. Later, we can do a further investigation on why they have been dropped. We will be relying heavily on Pandas to quickly generate the list

#### First, just like the previous codefile, we will accumulate the text data and the xml data together in a data frame and then preprocess the dataframe for our objective

In [2]:
import pandas as pd

textdata = pd.read_csv('Files_Directory/Edgar/textdata.csv', usecols = [0,1,2,3,5,6])
xmldata = pd.read_csv('Files_Directory/Edgar/xmldata.csv', usecols = [0,1,2,3,5,6])

xmldata.columns = list(textdata.columns.values) #making sure of uniformity in column names

df = pd.concat([textdata, xmldata]) #joining the two data frames

df.reset_index(drop = True) #Old index won't become new column

df.columns = list(df.columns.str.strip()) #cleaning out unnecessary spaces

df['Date'] = pd.to_datetime(df['Date'])

#### Again lets get a look and feel of the data

In [3]:
df.head(30)

,Fund Name,Date,Name of Stock,Type,Value,Shares
0,Adirondack_Funds,2013-05-06,ABBOTT LABS,COM,241,6
1,Adirondack_Funds,2013-05-06,ABBVIE INC,COM,278,6825
2,Adirondack_Funds,2013-05-06,AERCAP HOLDINGS NV,SHS,1326,85810
3,Adirondack_Funds,2013-05-06,AEROPOSTALE,COM,925,67987
4,Adirondack_Funds,2013-05-06,ALBANY MOLECULAR RESH INC,COM,1199,114083
5,Adirondack_Funds,2013-05-06,ALCATEL-LUCENT,SPONSORED ADR,588,441740
6,Adirondack_Funds,2013-05-06,ALLSCRIPTS HEALTHCARE SOLUTN,COM,2592,190749
7,Adirondack_Funds,2013-05-06,ALTEVA,COM,201,21875
8,Adirondack_Funds,2013-05-06,ASSURED GUARANTY LTD,COM,1847,89600
9,Adirondack_Funds,2013-05-06,AT&T INC,COM,512,13950
10,Adirondack_Funds,2013-05-06,AUTOBYTEL INC,COM NEW,1156,266423
11,Adirondack_Funds,2013-05-06,AXT INC,COM,850,288999
12,Adirondack_Funds,2013-05-06,BEBE STORES INC,COM,1275,305808
13,Adirondack_Funds,2013-05-06,BENCHMARK ELECTRS INC,COM,1501,83288
14,Adirondack_Funds,2013-05-06,BOSTON SCIENTIFIC CORP,COM,520,66525
15,Adirondack_Funds,2013-05-06,BOULDER BRANDS INC,COM,1272,141450
16,Adirondack_Funds,2013-05-06,BROADRIDGE FINL SOLUTIONS IN,COM,1644,66200
17,Adirondack_Funds,2013-05-06,BROCADE COMMUNICATIONS SYS I,COM NEW,2345,406400
18,Adirondack_Funds,2013-05-06,BROOKLINE BANCORP INC DEL,COM,1843,201674
19,Adirondack_Funds,2013-05-06,CAL MAINE FOODS INC,COM NEW,740,17398
20,Adirondack_Funds,2013-05-06,CALLAWAY GOLF CO,COM,2295,346608
21,Adirondack_Funds,2013-05-06,CHRISTOPHER & BANKS CORP,COM,663,103163
22,Adirondack_Funds,2013-05-06,CNO FINL GROUP INC,COM,3028,264478
23,Adirondack_Funds,2013-05-06,COCA COLA BOTTLING CO CONS,COM,1924,31895
24,Adirondack_Funds,2013-05-06,COCA COLA ENTERPRISES INC NE,COM,500,13550
25,Adirondack_Funds,2013-05-06,COEUR D ALENE MINES CORP IDA,COM NEW,1043,55291
26,Adirondack_Funds,2013-05-06,COMVERSE INC,COM,964,34368
27,Adirondack_Funds,2013-05-06,CONSOLIDATED EDISON INC,COM,311,5100
28,Adirondack_Funds,2013-05-06,COSI INC,COM,560,811498
29,Adirondack_Funds,2013-05-06,COVANTA HLDG CORP,COM,1499,74400

In [4]:
df.shape

(4796, 6)

In [5]:
df.dtypes

Fund Name                object
Date             datetime64[ns]
Name of Stock            object
Type                     object
Value                    object
Shares                    int64
dtype: object

#### Let's get a list of the companies that where dropped by the mutual funds>

#### let's first find the oldest and most recent filings for each mutual fund:

In [6]:
f = {'Date':['max','min']}
df_max_min_date = df.groupby(['Fund Name'], sort = False, as_index = False).agg(f)
df_max_min_date.columns = ['Fund Name','max_date','min_date']
df_max_min_date

                         Fund Name   max_date   min_date
0                 Adirondack_Funds 2015-11-10 2013-05-06
1            ADVANCE_CAPITAL_I_INC 2016-11-01 2012-02-02
2                   Global_X_Funds 2011-02-14 2011-02-14
3  FENIMORE_ASSET_MANAGEMENT_TRUST 2013-10-10 2013-10-10

#### For some mutual funds we only have one filing date, so we drop them.

In [7]:
df_dropped = list(df_max_min_date['Fund Name'][df_max_min_date.max_date == df_max_min_date.min_date])
df_dropped

['Global_X_Funds', 'FENIMORE_ASSET_MANAGEMENT_TRUST']

In [8]:
df = df[~df['Fund Name'].isin(df_dropped)]

In [9]:
df

,Fund Name,Date,Name of Stock,Type,Value,Shares
0,Adirondack_Funds,2013-05-06,ABBOTT LABS,COM,241,6
1,Adirondack_Funds,2013-05-06,ABBVIE INC,COM,278,6825
2,Adirondack_Funds,2013-05-06,AERCAP HOLDINGS NV,SHS,1326,85810
3,Adirondack_Funds,2013-05-06,AEROPOSTALE,COM,925,67987
4,Adirondack_Funds,2013-05-06,ALBANY MOLECULAR RESH INC,COM,1199,114083
5,Adirondack_Funds,2013-05-06,ALCATEL-LUCENT,SPONSORED ADR,588,441740
6,Adirondack_Funds,2013-05-06,ALLSCRIPTS HEALTHCARE SOLUTN,COM,2592,190749
7,Adirondack_Funds,2013-05-06,ALTEVA,COM,201,21875
8,Adirondack_Funds,2013-05-06,ASSURED GUARANTY LTD,COM,1847,89600
9,Adirondack_Funds,2013-05-06,AT&T INC,COM,512,13950
10,Adirondack_Funds,2013-05-06,AUTOBYTEL INC,COM NEW,1156,266423
11,Adirondack_Funds,2013-05-06,AXT INC,COM,850,288999
12,Adirondack_Funds,2013-05-06,BEBE STORES INC,COM,1275,305808
13,Adirondack_Funds,2013-05-06,BENCHMARK ELECTRS INC,COM,1501,83288
14,Adirondack_Funds,2013-05-06,BOSTON SCIENTIFIC CORP,COM,520,66525
15,Adirondack_Funds,2013-05-06,BOULDER BRANDS INC,COM,1272,141450
16,Adirondack_Funds,2013-05-06,BROADRIDGE FINL SOLUTIONS IN,COM,1644,66200
17,Adirondack_Funds,2013-05-06,BROCADE COMMUNICATIONS SYS I,COM NEW,2345,406400
18,Adirondack_Funds,2013-05-06,BROOKLINE BANCORP INC DEL,COM,1843,201674
19,Adirondack_Funds,2013-05-06,CAL MAINE FOODS INC,COM NEW,740,17398
20,Adirondack_Funds,2013-05-06,CALLAWAY GOLF CO,COM,2295,346608
21,Adirondack_Funds,2013-05-06,CHRISTOPHER & BANKS CORP,COM,663,103163
22,Adirondack_Funds,2013-05-06,CNO FINL GROUP INC,COM,3028,264478
23,Adirondack_Funds,2013-05-06,COCA COLA BOTTLING CO CONS,COM,1924,31895
24,Adirondack_Funds,2013-05-06,COCA COLA ENTERPRISES INC NE,COM,500,13550
25,Adirondack_Funds,2013-05-06,COEUR D ALENE MINES CORP IDA,COM NEW,1043,55291
26,Adirondack_Funds,2013-05-06,COMVERSE INC,COM,964,34368
27,Adirondack_Funds,2013-05-06,CONSOLIDATED EDISON INC,COM,311,5100
28,Adirondack_Funds,2013-05-06,COSI INC,COM,560,811498
29,Adirondack_Funds,2013-05-06,COVANTA HLDG CORP,COM,1499,74400
...,...,...,...,...,...,...
2699,ADVANCE_CAPITAL_I_INC,2013-08-13,UTI WORLDWIDE INC.,COMMON STOCK,168,10200
2700,ADVANCE_CAPITAL_I_INC,2013-08-13,UNITED TECHNOLOGIES CORPORATION,COMMON STOCK,836,9000
2701,ADVANCE_CAPITAL_I_INC,2013-08-13,UNIVERSAL CORP,COMMON STOCK,255,4400
2702,ADVANCE_CAPITAL_I_INC,2013-08-13,VISA INC,COMMON STOCK,914,5000
2703,ADVANCE_CAPITAL_I_INC,2013-08-13,VALSPAR CORPORATION,COMMON STOCK,401,6200
2704,ADVANCE_CAPITAL_I_INC,2013-08-13,VALERO ENERGY CORP,COMMON STOCK,725,20840
2705,ADVANCE_CAPITAL_I_INC,2013-08-13,VALLEY NATIONAL BANC,COMMON STOCK,183,19300
2706,ADVANCE_CAPITAL_I_INC,2013-08-13,VALMONT INDUSTRIES,COMMON STOCK,444,3100
2707,ADVANCE_CAPITAL_I_INC,2013-08-13,VODAFONE GROUP PLC,COMMON STOCK,652,22690
2708,ADVANCE_CAPITAL_I_INC,2013-08-13,VERTEX PHARMA.,COMMON STOCK,1385,17300
2709,ADVANCE_CAPITAL_I_INC,2013-08-13,VECTREN CORPORATION,COMMON STOCK,264,7800
2710,ADVANCE_CAPITAL_I_INC,2013-08-13,VERIZON COMM,COMMON STOCK,847,16830
2711,ADVANCE_CAPITAL_I_INC,2013-08-13,WABTEC,COMMON STOCK,481,9000
2712,ADVANCE_CAPITAL_I_INC,2013-08-13,WASHINGTON FEDERAL,COMMON STOCK,194,10300
2713,ADVANCE_CAPITAL_I_INC,2013-08-13,WEBSTER FINANCIAL,COMMON STOCK,360,14000
2714,ADVANCE_CAPITAL_I_INC,2013-08-13,WELLCARE HEALTH PLAN,COMMON STOCK,372,6700
2715,ADVANCE_CAPITAL_I_INC,2013-08-13,WASTE CONNECTIONS,COMMON STOCK,490,11900
2716,ADVANCE_CAPITAL_I_INC,2013-08-13,WELLS FARGO,COMMON STOCK,1387,33620
2717,ADVANCE_CAPITAL_I_INC,2013-08-13,WHIRLPOOL CORPORATIO,COMMON STOCK,405,3540
2718,ADVANCE_CAPITAL_I_INC,2013-08-13,WAL-MART,COMMON STOCK,852,11440
2719,ADVANCE_CAPITAL_I_INC,2013-08-13,WESTAR ENERGY INC,COMMON STOCK,384,12000
2720,ADVANCE_CAPITAL_I_INC,2013-08-13,WR BERKLEY CORP,COMMON STOCK,437,10700
2721,ADVANCE_CAPITAL_I_INC,2013-08-13,WILLIAMS-SONOMA INC .*,COMMON STOCK,469,8400
2722,ADVANCE_CAPITAL_I_INC,2013-08-13,AQUA AMERICA INC.,COMMON STOCK,410,13100
2723,ADVANCE_CAPITAL_I_INC,2013-08-13,WHITEWAVE FOODS CO,COMMON STOCK,221,13600
2724,ADVANCE_CAPITAL_I_INC,2013-08-13,WOODWARD INC.,COMMON STOCK,228,5700
2725,ADVANCE_CAPITAL_I_INC,2013-08-13,CIMAREX ENERGY CO,COMMON STOCK,526,8100
2726,ADVANCE_CAPITAL_I_INC,2013-08-13,EXXON MOBIL CORP.,COMMON STOCK,2292,25373
2727,ADVANCE_CAPITAL_I_INC,2013-08-13,ALLEGHANY CORP,COMMON STOCK,422,1100
2728,ADVANCE_CAPITAL_I_INC,2013-08-13,ZEBRA TECHNOLOGIES,COMMON STOCK,217,5000

In [10]:
Fund = []
Date = []
Dropped_Companies = []

for fund in list(df['Fund Name'].unique()):
    company_df = df[df['Fund Name'] == fund]
    company_dates = list(df[df['Fund Name']==fund]["Date"].sort_values().unique())
    
    for date_location in range(1,len(company_dates)):
        
        last_date = company_dates[date_location-1]
        current_date = company_dates[date_location]
        
        companies_dropped = list(set(company_df[company_df['Date']==last_date]['Name of Stock']) \
                                 - set(company_df[company_df['Date']==current_date]['Name of Stock']))
            
        Fund.extend([fund] * len(companies_dropped))
        Date.extend([company_dates[date_location]] * len(companies_dropped))
        Dropped_Companies.extend(companies_dropped)

In [11]:
len(Dropped_Companies)

1420

In [12]:
Dropped_Companies[:10]

['AERCAP HOLDINGS NV',
 'ALBANY MOLECULAR RESH INC',
 'IAC INTERACTIVECORP',
 'NN INC',
 'MATRIX SVC CO',
 'TRIQUINT SEMICONDUCTOR INC',
 'HARDINGE INC',
 'KEYNOTE SYS INC',
 'SPRINT NEXTEL CORP',
 'YAHOO INC']

In [13]:
Final_DF = pd.DataFrame({'Mutual Fund':Fund, 'Drop Date': Date , 'Company Name': Dropped_Companies})

#### Now to write this dataframe down to a CSV:

In [14]:
Final_DF.to_csv('Files_Directory/Edgar/Dropped Investments.csv')